### ISSUE TITLE
Not working on strike price with a period

### ISSUE THREAD

**Issue by kashivis** [RodSalazar/getOptionPrice-Google-Apps-Script#1]
Hi,

The code is wonderful, but it does not work on strike prices with decimals in them - e.g.: `getOptionPrice(AMZN MAY 24 $677.5 PUT)`

Can you help to fix this?

Regards

**Comment by kashivis** [comment]
In the function getYahooOptionTicker((ticker, month, day, year, strike, type)...

if you replace:
` //strike = parseInt(strike, 10)*1000;`

...with...:
`  strike = parseFloat(strike).toFixed(2)*1000;`

...your program works beautifully....

**Comment by RodSalazar** [comment]
Thanks!
